name: swag-labs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Google Chrome e ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable chromium-chromedriver
          echo "Google Chrome e ChromeDriver instalados com sucesso!"
          google-chrome --version
          chromedriver --version

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruamel.yaml

      - name: Executar Testes com Robot Framework
        env:
          ROBOT_BROWSER: chrome
        run: |
          mkdir -p results
          robot -d results tests/

      - name: Fazer upload dos relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: results/
          retention-days: 7
