name: swag-labs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl google-chrome-stable

      - name: Instalar dependências do projeto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager ruamel.yaml

      - name: Configurar ChromeDriver
        run: |
          python -c "from selenium import webdriver; from webdriver_manager.chrome import ChromeDriverManager; options = webdriver.ChromeOptions(); options.binary_location = '/usr/bin/google-chrome'; driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)"

      - name: Executar Testes com Robot Framework
        run: |
          mkdir -p results
          robot -d results tests/

      - name: Fazer upload dos relatórios de teste
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-results
          path: results/
          retention-days: 7
